# examples of WRONG values of single fields (or field combinations)
# with explanations
intro1: "DO NOT use values like the following in the output!:"
ref_value_more: |
                "ref_value": "more"
                # WRONG: ref_value must be an absolute quantity
copiotroph_type: |
  'group_name': 'Copiotroph',
  'group_type': 'biological_interaction',
  # WRONG: 'Copiotroph' is not a kind of biological interaction

